# Generated by Django 2.1.9 on 2019-08-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('fullnameemail', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('birhday', models.DateField()),
            ],
        ),
    ]
