# Generated by Django 2.1.9 on 2019-08-03 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c21', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='fullnameemail',
            new_name='email',
        ),
    ]
